create table if not exists public.games (
  id bigint generated by default as identity primary key,
  name text not null,
  platform text not null,
  score numeric(3, 1) not null check (score >= 0 and score <= 10),
  image_url text not null,
  created_at timestamptz not null default now(),
  unique (name, platform)
);

alter table public.games enable row level security;

revoke insert, update, delete on table public.games from anon, authenticated;
grant select on table public.games to anon, authenticated;

drop policy if exists "Anyone can read games" on public.games;
create policy "Anyone can read games"
  on public.games
  for select
  to anon, authenticated
  using (true);

insert into public.games (name, platform, score, image_url) values
  ('The Legend of Zelda: Breath of the Wild', 'Nintendo Switch', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3p2d.jpg'),
  ('God of War Ragnarök', 'PlayStation 5', 8.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/coba3d.jpg'),
  ('Forza Horizon 5', 'Xbox Series X|S', 8.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3ofx.jpg'),
  ('Minecraft', 'PC', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8fu7.jpg'),
  ('Elden Ring', 'Todas plataformas', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg'),
  ('Super Mario Odyssey', 'Nintendo Switch', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1mxf.jpg'),
  ('The Witcher 3: Wild Hunt', 'PC', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/coaarl.jpg'),
  ('Halo Infinite', 'Xbox Series X|S', 8.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2dto.jpg'),
  ('Cyberpunk 2077', 'PC', 7.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/coaih8.jpg'),
  ('Red Dead Redemption 2', 'PlayStation 4', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.jpg'),
  ('Horizon Zero Dawn', 'PlayStation 4', 8.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2una.jpg'),
  ('The Legend of Zelda: Ocarina of Time', 'Nintendo 64', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3nnx.jpg'),
  ('Super Smash Bros. Ultimate', 'Nintendo Switch', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2255.jpg'),
  ('Call of Duty 4: Modern Warfare', 'Xbox 360', 8.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1wko.jpg'),
  ('The Last of Us Part II', 'PlayStation 4', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5ziw.jpg'),
  ('Animal Crossing: New Horizons', 'Nintendo Switch', 9.5, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3wls.jpg'),
  ('Pokemon Pokopia', 'Nintendo Switch 2', 8.5, 'https://images.igdb.com/igdb/image/upload/t_cover_big/cobbur.jpg'),
  ('Halo Combat Evolved', 'Xbox', 8.5, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2r2r.jpg'),
  ('Halo 2', 'Xbox', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1x77.jpg'),
  ('Halo 3', 'Xbox 360', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1xhc.jpg'),
  ('Halo 4', 'Xbox 360', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1xhf.jpg'),
  ('Halo 5: Guardians', 'Xbox One', 7.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1xhg.jpg'),
  ('Halo Wars', 'Xbox 360', 7.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1wc0.jpg'),
  ('Halo Wars 2', 'Xbox One', 8.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2807.jpg'),
  ('Halo: Reach', 'Xbox 360', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1xha.jpg'),
  ('Halo 3: ODST', 'Xbox 360', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1xhh.jpg'),
  ('Halo: Combat Evolved Anniversary', 'Xbox 360', 7.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1xhb.jpg'),
  ('Halo: Spartan Strike', 'Xbox 360', 6.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1ver.jpg'),
  ('Halo: Spartan Assault', 'Xbox 360', 6.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1xi3.jpg'),
  ('Call of Duty: Black Ops II', 'Xbox 360', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1wkv.jpg'),
  ('Call of Duty: Black Ops III', 'Xbox One', 7.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co20yw.jpg'),
  ('Hong Kong 97', 'Super Nintendo', 2.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2uwd.jpg'),
  ('Super Mario 64', 'Nintendo 64', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co721v.jpg'),
  ('Five Nights at Freddy''s', 'PC', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8efb.jpg'),
  ('The Legend of Zelda: Majora''s Mask', 'Nintendo 64', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3pah.jpg'),
  ('Kingdom Come: Deliverance', 'PC', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4aqi.jpg'),
  ('The Elder Scrolls V: Skyrim', 'PC', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/cocs1l.jpg'),
  ('Kingdom Come: Deliverance II', 'PC', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8qmv.jpg'),
  ('Outer Wilds', 'PC', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co65ac.jpg'),
  ('Hollow Knight', 'PC', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/cobfzp.jpg'),
  ('Hollow Knight: Silksong', 'PC', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/cobebu.jpg'),
  ('Life is Strange', 'PC', 9.5, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r8e.jpg'),
  ('Pokemon: Fire Red', 'Game Boy', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1ziq.jpg'),
  ('Marvel''s Spider-Man', 'PlayStation 4', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r77.jpg'),
  ('Marvel''s Wolverine', 'PlayStation 5', 5.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/cob5mk.jpg'),
  ('Titanfall 2', 'PC', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/fhbeilnghyhhmjqhinqa.jpg'),
  ('Undertale', 'PC', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/cob1t2.jpg'),
  ('Lego Marvel Super Heroes', 'PC', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5bze.jpg'),
  ('Persona 3: Reload', 'Todas Plataformas', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/coc4jz.jpg'),
  ('Clair Obscur: Expedition 33', 'PC', 10.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9gam.jpg'),
  ('Resident Evil 5', 'PC', 7.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/cobtgs.jpg'),
  ('Beyond Two Souls', 'PlayStation 3', 7.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8r4w.jpg'),
  ('Detroit: Become Human', 'PlayStation 4', 8.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/cocot9.jpg'),
  ('Heavy Rain', 'PlayStation 3', 8.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/coaajv.jpg'),
  ('The Last of Us', 'PlayStation 3', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7f.jpg'),
  ('The Legend of Zelda: A Link between Worlds', 'Nintendo 3DS', 9.0, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3p0j.jpg')
on conflict (name, platform) do nothing;
